### ISSUE TITLE
Please tell me how to install the app into the ledger device. The installation failed according to the build.md document.

### ISSUE THREAD

**Issue by XxxxYxxx** [LedgerHQ/app-starknet#16]
bash-5.1# cargo ledger build --load  nanosplus -- --no-default-features
Use Rust nightly toolchain: nightly-2023-11-10
warning: Patch `ledger_device_sdk v1.5.0 (/app/ledger-device-rust-sdk/ledger_device_sdk)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
   Compiling proc-macro2 v1.0.78
   Compiling compiler_builtins v0.1.103
   Compiling unicode-ident v1.0.10
   Compiling glob v0.3.1
   Compiling libc v0.2.153
   Compiling rustix v0.38.31
   Compiling core v0.0.0 (/opt/rustup/toolchains/nightly-2023-11-10-x86_64-unknown-linux-musl/lib/rustlib/src/rust/library/core)
   Compiling prettyplease v0.2.16
   Compiling cfg-if v1.0.0
   Compiling minimal-lexical v0.2.1
   Compiling bitflags v2.4.2
   Compiling regex-syntax v0.8.2
   Compiling memchr v2.7.1
   Compiling linux-raw-sys v0.4.13
   Compiling libloading v0.8.1
   Compiling clang-sys v1.7.0
   Compiling home v0.5.9
   Compiling bindgen v0.65.1
   Compiling quote v1.0.35
   Compiling either v1.10.0
   Compiling syn v2.0.50
   Compiling nom v7.1.3
   Compiling lazy_static v1.4.0
   Compiling log v0.4.20
   Compiling rustc-hash v1.1.0
   Compiling lazycell v1.3.0
   Compiling peeking_take_while v0.1.2
   Compiling bitflags v1.3.2
   Compiling shlex v1.3.0
   Compiling cc v1.0.79
   Compiling syn v1.0.109
   Compiling autocfg v1.1.0
   Compiling num-traits v0.2.15
   Compiling weezl v0.1.7
   Compiling regex-automata v0.4.5
   Compiling color_quant v1.1.0
   Compiling which v4.4.2
   Compiling cexpr v0.6.0
   Compiling gif v0.11.4
   Compiling ledger_device_sdk v1.7.1
   Compiling regex v1.10.3
   Compiling include_gif v1.0.1 (/app/ledger-device-rust-sdk/include_gif)
   Compiling ledger_secure_sdk_sys v1.2.0 (/app/ledger-device-rust-sdk/ledger_secure_sdk_sys)
   Compiling rustc-std-workspace-core v1.99.0 (/opt/rustup/toolchains/nightly-2023-11-10-x86_64-unknown-linux-musl/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling numtoa v0.2.4
   Compiling rand_core v0.6.4
   Compiling zeroize v1.7.0
warning: ledger_secure_sdk_sys@1.2.0: Device is NanoSPlus
warning: ledger_secure_sdk_sys@1.2.0: API_LEVEL is 5
warning: ledger_secure_sdk_sys@1.2.0: TARGET_ID is 0x33100004
warning: ledger_secure_sdk_sys@1.2.0: TARGET_NAME is TARGET_NANOS2
warning: ledger_secure_sdk_sys@1.2.0: C_SDK_NAME is ledger-secure-sdk
warning: ledger_secure_sdk_sys@1.2.0: C_SDK_HASH is 48bb8d493548f840ddd261bbe60930f3f5966e7b
warning: ledger_secure_sdk_sys@1.2.0: C_SDK_VERSION is v5.10.0
   Compiling starknet v1.0.0 (/app/app-starknet)
    Finished release [optimized] target(s) in 21.68s
   text    data     bss     dec     hex filename
  27624       0    1904   29528    7358 /app/app-starknet/target/nanosplus/release/starknet
Dumping APDU installation file to /app/app-starknet/target/nanosplus/release/starknet.apdu
[WARNING] JSON files will be deprecated in future version
[WARNING] JSON files will be deprecated in future version
Traceback (most recent call last):
  File "/usr/bin/ledgerctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ledgerwallet/ledgerctl.py", line 206, in install_app
    client = get_client()
  File "/usr/lib/python3.9/site-packages/ledgerwallet/ledgerctl.py", line 108, in get_client
    return LedgerClient(private_key=get_private_key())
  File "/usr/lib/python3.9/site-packages/ledgerwallet/client.py", line 127, in __init__
    self.device.open()
  File "/usr/lib/python3.9/site-packages/ledgerwallet/transport/hid.py", line 30, in open
    self.device.open_path(self.path)
  File "hidraw.pyx", line 158, in hid.device.open_path
OSError: open failed

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @XxxxYxxx

**Comment by yogh333** [comment]
Please see Readme file about how to build and install.
