### ISSUE TITLE
"Unable to find image 'ghcr.io/ledgerhq:latest' locally"

### ISSUE THREAD

**Issue by danimesq** [LedgerHQ/app-starknet#21]
> app-starknet on  develop is 📦 v1.1.1 via 🦀 v1.72.0 
> ❯ sudo docker run --rm -it -v "$(pwd -P):/apps" ghcr.io/ledgerhq ledger-app-builder/ledger-app-builder
> Unable to find image 'ghcr.io/ledgerhq:latest' locally
> docker: Error response from daemon: Head "https://ghcr.io/v2/ledgerhq/manifests/latest": name invalid.
> See 'docker run --help'.

**Comment by Admin661** [comment]
Hi, is the issue resolved yet? You'll have to rectify with the ledger loptimal weblink and try it again.

**Comment by yogh333** [comment]
there is a typo and it should be:
`docker run --rm -it -v "$(pwd -P):/apps" ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder`
