### ISSUE TITLE
Live soon?

### ISSUE THREAD

**Issue by palomato** [LedgerHQ/app-starknet#24]
@yogh333 appreciate all your work.
This app is available in ledger live developer mode. 
After two years of dev, will it be available on ledger live official soon?

**Comment by adrienlacombe** [comment]
@palomato dev mode is official, it is just that you sign a hash right now with the app but we are working on improving that.

**Comment by palomato** [comment]
Got it, thank you.

**Comment by palomato** [comment]
Closed.
