### ISSUE TITLE
Clear-sign ETH/STRK transfer

### ISSUE THREAD

**Issue by yogh333** [LedgerHQ/app-starknet#26]
Scope:
- To be able to clear sign any transfer of ETH or STRK ERC-20 tokens on Starknet. For a Tx which triggers an ERC-20 transfer, the destination address and token amount shall be displayed on device's screen so they can be reviewed and confirmed by the user before signing the Tx
- Tx version to be supported is [v3](https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#v3_transaction_fields)
- Clear sign ERC-20 token transfer should be available for all devices supporting the Starknet application (Nano S+, NanoX, Stax)
- For any other Tx (i.e different from "ERC-20 transfer"), blind signing (i.e signing the [Poseidon](https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#v3_transaction_fields) hash of the transaction) should be proposed, but warning the user about the risk when using blind signing.

**Comment by yogh333** [comment]
Specifications update:

- when blind signing a Tx, the Tx hash will be displayed on device screen, along with warnings for the user about using blind signing,
- For clear signing ERC-20 (STRK or ETH) token transfer , the following info will be displayed to be confirmed by the user:
`From`
`Amount`
`Ticker`
`To`
`Max fees`.

**Comment by yogh333** [comment]
see #28

**Comment by yogh333** [comment]
Following some internal discussions and after feedbacks from Starknet wallet developers (Argent-X, Braavos), it has been decided to extend the first Milestone:

1. To support **Tx v1 signing** as it is still used (despite being signalled as **deprecated** on [Starknet official documentation](https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#v1_deprecated_transaction_fields)) when end-user wants to pay fees in ETH (Tx v3 is used when fees to be paid in STRK token). Tx v1 will be clear-signed when dealing with ETH or STRK transfers, displaying same info as for Tx v3 (`From`, `Amount`, `Ticker`, `To`, `Max Fees`) or blind signed for every other types of operations (Pedersen hash of the Tx will be displayed in that case).
2. To support **blind-signing of off-chain message** (see [SNIP-12](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md)) through a new signMessage() function: message hash will be computed by the client (using `starknet.js`) and the hash will be sent to the device to be displayed and signed if end-user confirms.
3. Both 1. and 2. items require to update the [starknet-js](https://github.com/LedgerHQ/starknet-js-client) client, and thus a new release of this client will be also performed and integrated by Starknet wallets in order to support the next app version.

**Comment by dhruvkelawala** [comment]
Lgtm!

**Comment by yogh333** [comment]
See #32
