### ISSUE TITLE
Invalid `CLA` for sign command 1 and 2 in APDU docs

### ISSUE THREAD

**Issue by franciszekjob** [LedgerHQ/app-starknet#27]
Hey, I think there might be an invalid CLA in sign command 1 and 2 in [APDU docs](https://github.com/LedgerHQ/app-starknet/blob/develop/docs/apdu.md). There should be  `0x5A` instead of `0x80`.

**Comment by franciszekjob** [comment]
@yogh333 ?

**Comment by yogh333** [comment]
@franciszekjob This has been fixed in the last release ;)
