### ISSUE TITLE
Signing other transaction types

### ISSUE THREAD

**Issue by franciszekjob** [LedgerHQ/app-starknet#31]
Hi, updated APDU spec (after PR with clear-signing txs) does not include command with ins=0x02 which enabled blind signing txs. This makes sense, but it looks like current interface allows to sign only invoke transactions (?). Will it be possible to sign other types of txs, e.g. deploy account, declare?
Also, I found [this JS example](https://github.com/LedgerHQ/starknet-js-client/blob/main/sample_app/index.js), but it's not working anymore, it's probably not up to the latest version of Starknet ledger app. 

Would appreciate your reply, as currently our ledger signing interface has been highly affected by these changes and I am not sure whether we have to rewrite it or will there be other changes in APDU spec allowing for some smaller adjustments on our side.
Thanks.

**Comment by yogh333** [comment]
Signing hash has been re-enabled in last release (`2.1.0`) of Starknet app (see #32) and can be used to blind sign Deploy or Declare txs as well as SNIP-12 message (pre-hashed by the JS client). You shall use the last [JS client](https://github.com/LedgerHQ/starknet-js-client) (`2.3.0`) with this last release.
