### ISSUE TITLE
How can I sideload the starknet-app on my ledger nano S?

### ISSUE THREAD

**Issue by 0xKawaka** [LedgerHQ/app-starknet#42]
I had the developer version and tried to install the official release but it doesn't support nano S.
I'm trying to install the previous version supporting nano S. How can I do that?

I tried to follow this tutorial https://www.youtube.com/watch?v=PxphfNWMGrY but the ledger extension doesn't recognize the app.

Any help would be highly appreciated as I'm going to get liquidated since I can't access my wallet.

**Comment by Emmaward090** [comment]
> I had the developer version and tried to install the official release but it doesn't support nano S. I'm trying to install the previous version supporting nano S. How can I do that?
> 
> I tried to follow this tutorial https://www.youtube.com/watch?v=PxphfNWMGrY but the ledger extension doesn't recognize the app.
> 
> Any help would be highly appreciated as I'm going to get liquidated since I can't access my wallet.



To sideload the StarkNet app on your Ledger Nano S, you can follow these general steps:

1. Install Ledger Live: Make sure you have the latest version of Ledger Live installed on your computer.

2. Enable Developer Mode: In Ledger Live, go to the settings and enable developer mode. This will allow you to install apps not available in the official app catalog.

3. Download the StarkNet App: You’ll need to find the StarkNet app's binary file (usually a `.bin` file). This might be available on the StarkNet GitHub repository or their official website.

4. Use the Ledger CLI: If you have the Ledger command line interface (CLI) installed, you can use it to install the app. Open your terminal and run the command:
   ```
   ledgerctl install --file path/to/starknet-app.bin
   ```
   Replace `path/to/starknet-app.bin` with the actual path to the downloaded app.

5. Check Installation: After the installation, you can check if the app is successfully installed by navigating to your Ledger device. 

6. Open the App: Finally, you can open the StarkNet app on your Ledger Nano S and start using it.

If you encounter any issues during the process, let me know, and I can help troubleshoot!
@0xKawaka

**Comment by adrienlacombe** [comment]
problem solved :)

**Comment by 0xKawaka** [comment]
Solved! Thank you for the help!
