### ISSUE TITLE
Building app fails for nanox device

### ISSUE THREAD

**Issue by franciszekjob** [LedgerHQ/app-starknet#45]
Hi, when running `cargo ledger build nanox` inside `ledger-app-dev-tools`Docker container, I get following error:

```
error: failed to run custom build command for `ledger_secure_sdk_sys v1.2.0`

Caused by:
  process didn't exit successfully: `/apps/target/release/build/ledger_secure_sdk_sys-8bbdea486eda8cb2/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=TARGET=nanox
  cargo:warning=Device is NanoX
  cargo:rerun-if-env-changed=LEDGER_SDK_PATH

  --- stderr
  thread 'main' panicked at /opt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ledger_secure_sdk_sys-1.2.0/build.rs:533:29:
  called `Result::unwrap()` on an `Err` value: MissingTargetId
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /opt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-ledger-1.5.1/src/main.rs:274:41:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is link to example CI run as reference:
https://github.com/software-mansion/starknet.py/actions/runs/12223165033/job/34094369053?pr=1527

I switched to nanos and it works fine, but wondering why it happens on nanox.

**Comment by yogh333** [comment]
@franciszekjob Hi, I've tried and it works fine. You have to `cd` into `starknet/` before and then call `cargo ledger build nanox`

**Comment by franciszekjob** [comment]
Thanks for reply @yogh333  - which version are you using? I build it from [this commit](https://github.com/LedgerHQ/app-starknet/commits/dd58c5c), don't think that's a problem though. (It stopped working just a few days ago)

**Comment by franciszekjob** [comment]
@yogh333 did you had a chance to see my reply?

**Comment by yogh333** [comment]
@franciszekjob Please use head of `develop` branch. Using old commit with last `dev-tools`container may be the reason of your issue

**Comment by franciszekjob** [comment]
@yogh333 changed images version to `3.41.0`, it works now, thanks for assistance 👍
